export const VOID_COMMAND_NAME = {
  addTests: "void.addTests",
  addTypes: "void.addTypes",
  conversationHistory: "void.conversationHistory",
  disable: "void.disable",
  embeddings: "void.embeddings",
  enable: "void.enable",
  review: "void.review",
  explain: "void.explain",
  focusSidebar: "void.sidebar.focus",
  generateDocs: "void.generateDocs",
  getGitCommitMessage: "void.getGitCommitMessage",
  hideBackButton: "void.hideBackButton",
  manageProviders: "void.manageProviders",
  manageTemplates: "void.manageTemplates",
  newConversation: "void.newConversation",
  openPanelChat: "void.openPanelChat",
  openChat: "void.openChat",
  refactor: "void.refactor",
  settings: "void.settings",
  stopGeneration: "void.stopGeneration",
  templateCompletion: "void.templateCompletion",
  templates: "void.templates",
  symmetryTab: "void.symmetry",
  addFileToContext: "void.addFileToContext",
  getContextFiles: "void.getContextFiles",
  addSelectionToContext: "void.addSelectionToContext"
}
